### PR TITLE
Returning _page as int

### PR DESCRIPTION
**Pull request by Lansoweb**
Fixing [#11](https://github.com/zendframework/zend-expressive-hal/issues/11)

### CODE REVIEW

**Comment by Lansoweb** [comment]
Oh sorry, will do it.

**Comment by Lansoweb** [comment]
@weierophinney Since to fix [#10](https://github.com/zendframework/zend-expressive-hal/issues/10) I will need to change the same file, do you prefer to include it here or should i create other PR?

**Comment by weierophinney** [comment]
@Lansoweb — the two issues are orthogonal; they affect the same area, but with different context. Create a different branch for that PR and submit it. If there are any conflicts, we can manage those after this one is merged.

**Comment by Lansoweb** [comment]
Great. Finishing the PR for [#10](https://github.com/zendframework/zend-expressive-hal/issues/10).

**Pull request merged**
